name: bonfire_crash_course
description: Beginners course to using Bonfire.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.19.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.5
  bonfire: ^3.0.0
  flame_audio: ^2.0.4
  flame_tiled: ^1.12.0
  flutter_riverpod: ^2.3.6
  macos_ui: ^2.0.2
  
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/audio/
    - assets/images/
    - assets/tiles/
